name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🛠 Improvements'
    labels:
      - 'improvement'
      - 'refactor'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking change'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
change-template: '- $TITLE ([#$NUMBER]($URL)) @$AUTHOR'
no-changes-template: '- No changes.'
template: |
  ## 📦 New Release

  **Version:** $NEXT_PATCH_VERSION

  ### What's New

  $CHANGES

  ### Contributors

  Thanks to the following people for contributing:

  $CONTRIBUTORS

  **Full Changelog**: [$PREVIOUS_TAG...$NEW_TAG]($COMPARE_URL)
